---
name:   SweetSweetBetrayal               # The application display name
short:  SweetSweetBetrayal                  # A shortened name for reference
appid:  com.smithereens.ssb  # Application identifier for Mac, iOS, Android
suffix: GC944B44

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)
icon:   icon.png

orientation: landscape              # The orientation for mobile devices

sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h

modules:
    - audio                         # We need sound
    - physics2                      # We need the physics libraries
    - scene2                        # We want the 2d UI
    - netcode
    - physics2::distrib
    - UIScene

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - android                   # Android Studio
    - apple                     # XCode (note macOS and iOS use one project)
    - windows                   # Windows Sisual Studio
    - cmake                     # This supports all Desktop platform GBA5AF6 GBA5AF6 GA5CAA5 GC9EE55 G607B7B5
